#!/bin/bash
#     GNU AFFERO GENERAL PUBLIC LICENSE
#        Version 3, 19 November 2007
#
#  Dryncs, Copy files serialized from local pc or remote pc.
#    Copyright (C) 2024  BIOS Tech
#
# You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#===============================================================================
#      What is this:
#
#          FILE: dryncs
#
#         USAGE: ./dryncs
#
#   DESCRIPTION: Copy Files Serialized listed from a text file to one local pc o remote pc
#
#       OPTIONS: in config file 'mdialog_conf'
#  REQUIREMENTS: rsync, dialog, bash 5.2, samba server, samba client, lsblk, blkid
#          BUGS: Dialog in the first database update the main menu closed.
#         NOTES: (Linux) For Remote copies add the resources you wanna share to smb.conf, (Windows) Just add the shared resources
#        AUTHOR: Erwin Castedo (blkid@protonmail.com)
#  ORGANIZATION: BIOS Tech (pc.biosxtreme.net)
#       CREATED: 13/07/2024 21:00
#      REVISION: 2.0
#===============================================================================
#
######################
#    CONFIGURACIÓN   #
######################
#
# set -e break if a error happen

set -e

# Config File

. ./mdialog_conf

#######################
#  FIN CONFIGURACIÓN  #
#######################

# submenu
# Updating database of files and dirs

submenu () {
  clear
  local PS3='Por favor escoga una opción: '
  local options=("Películas" "Música" "JUegos" "Apps" "Libros" "Comics" "Volver")
  local opt
  select opt in "${options[@]}"
  do
      case $opt in
          "Películas")
              if [ -f $fallrepos -a -d "$fsourcepath" ] ; then
                cd "$fsourcepath"
                find . -type f > "$fallrepos"
                sed -i 's/\.\///g' "$fallrepos"
                result=$(echo "DB Películas fallrepos Updated - Base de datos de Películas Actualizado")
                display_result "INFORME"
              else
                result=$(echo "Falló Actualización de las Películas,\n
revise la configuración de mdialog_conf\n
y las variables:\n
fallrepos\n
fsourcepath")
                display_result "INFORME DB PELÍCULAS"
              fi
              ;;
          "Música")
              if [ -f "$mallrepos" -a -d "$msourcepath" ]; then
                cd "$msourcepath"
                find . -type d > "$mallrepos"
                sed -i 's/\.\///g' "$mallrepos"
                result=$(echo "DB Music mallrepos Updated - Base de datos de Música Actualizada")
                display_result "INFORME"
              else
                result=$(echo "Falló Actualización de mallrepos, revise la configuración mdialog_conf")
                display_result "INFORME DB MÚSICA"
              fi
              ;;
          "Juegos")
              if [ -f "$jallrepos" -a -d "$jsourcepath" ]; then
                cd "$jsourcepath"
                find . -type d > "$jallrepos"
                sed -i 's/\.\///g' "$jallrepos"
                result=$(echo "DB Apps jallrepos Updated - Base de datos de Juegos Actualizada")
                display_result "INFORME"
              else
                result=$(echo "Falló Actualización de jallrepos, revise la configuración mdialog_conf")
                display_result "INFORME DB JUEGOS"
              fi
              ;;
          "Apps")
              if [ -f "$aallrepos" -a -d "$asourcepath" ]; then
                cd "$asourcepath"
                find . -type d > "$aallrepos"
                sed -i 's/\.\///g' "$aallrepos"
                result=$(echo "DB Apps aallrepos Updated - Base de datos de Apps Actualizada")
                display_result "INFORME"
              else
                result=$(echo "Falló Actualización de aallrepos, revise la configuración mdialog_conf")
                display_result "INFORME DB APPS"
              fi
              ;;
          "Libros")
              if [ -f $lallrepos -a -d "$lsourcepath" ] ; then
                cd "$lsourcepath"
                find . -type f > "$lallrepos"
                sed -i 's/\.\///g' "$lallrepos"
                result=$(echo "DB Películas lallrepos Updated - Base de datos de los Libros Actualizado")
                display_result "INFORME"
              else
                result=$(echo "Falló Actualización de los Libros,\n
revise la configuración de mdialog_conf\n
y las variables:\n
lallrepos\n
lsourcepath")
                display_result "INFORME DB LIBROS"
              fi
              ;;
          "Comics")
              if [ -f $callrepos -a -d "$csourcepath" ] ; then
                cd "$csourcepath"
                find . -type f > "$callrepos"
                sed -i 's/\.\///g' "$callrepos"
                result=$(echo "DB Películas callrepos Updated - Base de datos de Comics Actualizado")
                display_result "INFORME"
              else
                result=$(echo "Falló Actualización de los Comics,\n
revise la configuración de mdialog_conf\n
y las variables:\n
callrepos\n
csourcepath")
                display_result "INFORME DB COMICS"
              fi
              ;;
          "Volver")
              return
              ;;
          *) echo "invalid option $REPLY";;
      esac
      return
  done
}
# while-menu-dialog: a menu driven system information program

# Status Button
DIALOG_CANCEL=1
DIALOG_ESC=255
HEIGHT=19
WIDTH=0

display_result() {
  dialog --title "$1" \
    --no-collapse \
    --msgbox "$result" 0 0
}

# MENU

while true; do
  exec 3>&1
  selection=$(dialog \
    --backtitle "Panel del Sistema" \
    --title "Menu" \
    --cancel-label "Salir" \
    --help-button \
    --menu "Seleccione una Opción:" "$HEIGHT" "$WIDTH" 4 \
    "1" "Listar Dispositivos Montados" \
    "2" "Listar las palabras para buscar y copiar" \
    "3" "Películas" \
    "4" "Música" \
    "5" "Juegos" \
    "6" "Apps" \
    "7" "Libros" \
    "8" "Comics" \
    "9" "Actualizar Bases de Datos" \
    "0" "Ver Archivos Copiados" \
    "10" "Configuración" \
    2>&1 1>&3)
    exit_status=$?
    exec 3>&-
    
# Button Status

  case $exit_status in
    $DIALOG_CANCEL)
      clear
      echo "Programa Terminado"
      exit
      ;;
    $DIALOG_ESC)
      clear
      echo "Programa Abortado" >&2
      exit 1
      ;;
  esac
  case $selection in
    1)
      result=$(lsblk -o +UUID,PARTUUID)
      display_result "Dispositivos Montados"
      ;;
    2)
      origen=$(dialog --stdout --title "Ruta Archivo db:" --fselect "$dialogorig" 15 125)
      pedido=$(cat "$origen")
      dialog --no-collapse --title "Lista de Pedido" --msgbox "$pedido" 0 0
      ;;
    3)
# MOVIES BY FILM ID
      counterc=0
      counterf=0
      regdate=$(date)
      cliente=$(dialog --stdout --title "Datos Cliente:" --inputbox "Nombre y Apellido (Prefijo):" 0 0)
      logcopy=$(echo -e "\n\n--Cliente: $cliente - $regdate" >> "$copiadoslog")
      logrip=$(echo -e "\n\n--Cliente: $cliente - $regdate" >> "$fallidoslog")
      destino=$(dialog --stdout --title "Seleccionar Carpeta Destino:" --fselect "$dialogdest" 45 125)
      origen=$(dialog --stdout --title "Ruta Lista (ej. fcid.txt)" --fselect "$dialogorig" 45 65)
      # radiolist
      pathrsyncing=$(dialog --stdout --title "RSYNC OPTION" --radiolist "Copiar el directorio/archivo con o sin el árbol de directorio" 0 70 0 \
		"1" "Sin Full Path rsync -ah ex: dir-N### or file-N###" on \
		"2" "Full Path rsync -ahR ex: /path1/to/others/target" off)
		if [ "$pathrsyncing" == 1 ]; then
      sed -i '/^[[:space:]]*$/d' "$origen"
			lowtoupcase=$(sed -i "s/f/F/g" "$origen")
			exec < "$origen"
			while read -r line
			do
				lct=$(cat "$fallrepos" | grep -iwm 1 "$line")
				lct2=$(grep -Piowm 1 "$line" "$fallrepos") # Extráe solo la palabra lct(F####) con -o usando regex de Pearl con -P, -m 1 para que imprima la primera coincidencia y no replique los repetidos en el archivo fallrepos
				if [ "$lct2" == "$line" ]; then
				# rsync copying with full path
					fuente="${fsourcepath}${lct}"
					rsync -ah --info=progress2 --log-file="$rsynclog" "$fuente" "$destino"
					copiados=$(echo -e "  * $line" >> "$copiadoslog")
					let counterc=counterc+1
				else
					fallidos=$(echo -e "  * $line" >> "$fallidoslog")
					let counterf=counterf+1
				fi
			done
		else
      sed -i '/^[[:space:]]*$/d' "$origen"
			lowtoupcase=$(sed -i "s/f/F/g" "$origen")
			exec < "$origen"
			while read -r line
			do
				lct=$(cat "$fallrepos" | grep -iwm 1 "$line")
				lct2=$(grep -Piowm 1 "$line" "$fallrepos") # Extráe solo la palabra lct(F####) con -o usando regex de Pearl con -P, -m 1 para que imprima la primera coincidencia y no replique los repetidos en el archivo fallrepos
				if [ "$lct2" == "$line" ]; then
				# rsync copying with full path
					fuente="${fsourcepath}./${lct}"
					rsync -ahR --info=progress2 --log-file="$rsynclog" "$fuente" "$destino"
					copiados=$(echo -e "  * $line" >> "$copiadoslog")
					let counterc=counterc+1
				else
          fallidos=$(echo -e "  * $line" >> "$fallidoslog")
					let counterf=counterf+1
				fi
			done
		fi
      let totalpedido=counterc+counterf
      pedido=$(cat "$origen")
      dialog --title "Copia Finalizada" \
      --msgbox "\n
	  ------------ Rutas ------------\n
        Lista ID's  : $origen\n
            Destino : $destino\n
	  ------------ Items ------------\n
       ----------------+-----\n
        Total Pedidos  |  $totalpedido   \n
       ----------------+-----\n
        Total Copiados |  $counterc   \n
       ----------------+-----\n
        total Fallidos |  $counterf   \n
       ----------------+-----\n
      Items Pedidos:\n
      $pedido\n\n" 0 0
      exec cat -n "$copiadoslog"
      ;;
    4)
# MUSIC BY FOLDER ALBUM
      counterc=0
      counterf=0
      regdate=$(date)
      cliente=$(dialog --stdout --title "Datos Cliente:" --inputbox "Nombre y Apellido (Prefijo):" 0 0)
      logcopy=$(echo -e "\n\n--Cliente: $cliente - $regdate" >> "$copiadoslog")
      logrip=$(echo -e "\n\n--Cliente: $cliente - $regdate" >> "$fallidoslog")
      destino=$(dialog --stdout --title "Seleccionar Carpeta Destino:" --fselect "$dialogdest" 45 125)
      origen=$(dialog --stdout --title "Ruta Lista (ej. mcid.txt)" --fselect "$dialogorig" 45 65)
      # radiolist
      pathrsyncing=$(dialog --stdout --title "RSYNC OPTION" --radiolist "Copiar el directorio/archivo con o sin el árbol de directorio" 0 70 0 \
		"1" "Sin Full Path rsync -ah ex: dir-N### or file-N###" on \
		"2" "Full Path rsync -ahR ex: /path1/to/others/target" off)
		if [ "$pathrsyncing" == 1 ]; then
        sed -i '/^[[:space:]]*$/d' "$origen"
			  lowtoupcase=$(sed -i "s/m/M/g" "$origen")
			  exec < "$origen"
			  while read -r line
			  do
				lct=$(cat "$mallrepos" | grep -iwm 1 "$line")
				lct2=$(grep -Piowm 1 "$line" "$mallrepos") # Extráe solo la palabra lct(M####) con -o usando regex de Pearl con -P, -m 1 para que imprima la primera coincidencia y no replique los repetidos en el archivo mallrepos
				if [ "$lct2" == "$line" ]; then
				# rsync copying without full path
				  fuente="${msourcepath}${lct}"
				  rsync -ah --info=progress2 --log-file="$rsynclog" "$fuente" "$destino"
				  copiados=$(echo -e "  * $line" >> "$copiadoslog")
				  let counterc=counterc+1
				else
				  fallidos=$(echo -e "  * $line" >> "$fallidoslog")
				  let counterf=counterf+1
				fi
			  done
		else
        sed -i '/^[[:space:]]*$/d' "$origen"
				lowtoupcase=$(sed -i "s/m/M/g" "$origen")
				exec < "$origen"
				while read -r line
				do
					lct=$(cat "$mallrepos" | grep -iwm 1 "$line")
					lct2=$(grep -Piowm 1 "$line" "$mallrepos") # Extráe solo la palabra lct(M####) con -o usando regex de Pearl con -P, -m 1 para que imprima la primera coincidencia y no replique los repetidos en el archivo mallrepos
					if [ "$lct2" == "$line" ]; then
					# rsync copying with full path
						fuente="${msourcepath}./${lct}"
						rsync -ahR --info=progress2 --log-file="$rsynclog" "$fuente" "$destino"
						copiados=$(echo -e "  * $line" >> "$copiadoslog")
						let counterc=counterc+1
					else
						fallidos=$(echo -e "  * $line" >> "$fallidoslog")
						let counterf=counterf+1
					fi
				done
		fi
      let totalpedido=counterc+counterf
      pedido=$(cat "$origen")
      dialog --title "Copia Finalizada" \
      --msgbox "\n
	  ------------ Rutas ------------\n
        Lista ID's  : $origen\n
            Destino : $destino\n
	  ------------ Items ------------\n
       ----------------+-----\n
        Total Pedidos  |  $totalpedido   \n
       ----------------+-----\n
        Total Copiados |  $counterc   \n
       ----------------+-----\n
        total Fallidos |  $counterf   \n
       ----------------+-----\n
      Items Pedidos:\n
      $pedido\n\n" 0 0
      exec cat -n "$copiadoslog"
      ;;
    5)
# JUEGOS BY FOLDER    
      counterc=0
      counterf=0
      regdate=$(date)
      cliente=$(dialog --stdout --title "Datos Cliente:" --inputbox "Nombre y Apellido (Prefijo):" 0 0)
      logcopy=$(echo -e "\n\n--Cliente: $cliente - $regdate" >> "$copiadoslog")
      logrip=$(echo -e "\n\n--Cliente: $cliente - $regdate" >> "$fallidoslog")
      destino=$(dialog --stdout --title "Seleccionar Carpeta Destino:" --fselect "$dialogdest" 45 125)
      origen=$(dialog --stdout --title "Ruta Lista (ej. jcid.txt)" --fselect "$dialogorig" 45 65)
      # radiolist
      pathrsyncing=$(dialog --stdout --title "RSYNC OPTION" --radiolist "Copiar el directorio/archivo con o sin el árbol de directorio" 0 70 0 \
		"1" "Sin Full Path rsync -ah ex: dir-N### or file-N###" on \
		"2" "Full Path rsync -ahR ex: /path1/to/others/target" off)
		if [ "$pathrsyncing" == 1 ]; then
      sed -i '/^[[:space:]]*$/d' "$origen"
			lowtoupcase=$(sed -i "s/j/J/g" "$origen")
			exec < "$origen"
			while read -r line
			do
				lct=$(cat "$jallrepos" | grep -iwm 1 "$line")
				lct2=$(grep -Piowm 1 "$line" "$jallrepos") # Extráe solo la palabra lct(J####) con -o usando regex de Pearl con -P, -m 1 para que imprima la primera coincidencia y no replique los repetidos en el archivo jallrepos
				if [ "$lct2" == "$line" ]; then
				# rsync copying with full path
					fuente="${jsourcepath}${lct}"
					rsync -ah --info=progress2 --log-file="$rsynclog" "$fuente" "$destino"
					copiados=$(echo -e "  * $line" >> "$copiadoslog")
					let counterc=counterc+1
				else
					fallidos=$(echo -e "  * $line" >> "$fallidoslog")
					let counterf=counterf+1
				fi
			done
		else
      sed -i '/^[[:space:]]*$/d' "$origen"
			lowtoupcase=$(sed -i "s/j/J/g" "$origen")
			exec < "$origen"
			while read -r line
			do
				lct=$(cat "$jallrepos" | grep -iwm 1 "$line")
				lct2=$(grep -Piowm 1 "$line" "$jallrepos") # Extráe solo la palabra lct(J####) con -o usando regex de Pearl con -P, -m 1 para que imprima la primera coincidencia y no replique los repetidos en el archivo jallrepos
				if [ "$lct2" == "$line" ]; then
				# rsync copying with full path
					fuente="${jsourcepath}./${lct}"
					rsync -ahR --info=progress2 --log-file="$rsynclog" "$fuente" "$destino"
					copiados=$(echo -e "  * $line" >> "$copiadoslog")
					let counterc=counterc+1
				else
					fallidos=$(echo -e "  * $line" >> "$fallidoslog")
					let counterf=counterf+1
				fi
			done
		fi
      let totalpedido=counterc+counterf
      pedido=$(cat "$origen")
      dialog --title "Copia Finalizada" \
      --msgbox "\n
	  ------------ Rutas ------------\n
        Lista ID's  : $origen\n
            Destino : $destino\n
	  ------------ Items ------------\n
       ----------------+-----\n
        Total Pedidos  |  $totalpedido   \n
       ----------------+-----\n
        Total Copiados |  $counterc   \n
       ----------------+-----\n
        total Fallidos |  $counterf   \n
       ----------------+-----\n
      Items Pedidos:\n
      $pedido\n\n" 0 0
      exec cat -n "$copiadoslog"
      ;;
    6)
# APPS BY FOLDER
      counterc=0
      counterf=0
      regdate=$(date)
      cliente=$(dialog --stdout --title "Datos Cliente:" --inputbox "Nombre y Apellido (Prefijo):" 0 0)
      logcopy=$(echo -e "\n\n--Cliente: $cliente - $regdate" >> "$copiadoslog")
      logrip=$(echo -e "\n\n--Cliente: $cliente - $regdate" >> "$fallidoslog")
      destino=$(dialog --stdout --title "Seleccionar Carpeta Destino:" --fselect "$dialogdest" 45 125)
      origen=$(dialog --stdout --title "Ruta Lista (ej. acid.txt)" --fselect "$dialogorig" 45 65)
      # radiolist
      pathrsyncing=$(dialog --stdout --title "RSYNC OPTION" --radiolist "Copiar el directorio/archivo con o sin el árbol de directorio" 0 70 0 \
		"1" "Sin Full Path rsync -ah ex: dir-N### or file-N###" on \
		"2" "Full Path rsync -ahR ex: /path1/to/others/target" off)
		if [ "$pathrsyncing" == 1 ]; then
      sed -i '/^[[:space:]]*$/d' "$origen"
			lowtoupcase=$(sed -i "s/a/A/g" "$origen")
			exec < "$origen"
			while read -r line
			do
				lct=$(cat "$aallrepos" | grep -iwm 1 "$line")
				lct2=$(grep -Piowm 1 "$line" "$aallrepos") # Extráe solo la palabra lct(A####) con -o usando regex de Pearl con -P, -m 1 para que imprima la primera coincidencia y no replique los repetidos en el archivo aallrepos
				if [ "$lct2" == "$line" ]; then
				# rsync copying with full path
					fuente="${asourcepath}${lct}"
					rsync -ah --info=progress2 --log-file="$rsynclog" "$fuente" "$destino"
					copiados=$(echo -e "  * $line" >> "$copiadoslog")
					let counterc=counterc+1
				else
					fallidos=$(echo -e "  * $line" >> "$fallidoslog")
					let counterf=counterf+1
				fi
			done
		else
      sed -i '/^[[:space:]]*$/d' "$origen"
			lowtoupcase=$(sed -i "s/a/A/g" "$origen")
			exec < "$origen"
			while read -r line
			do
				lct=$(cat "$aallrepos" | grep -iwm 1 "$line")
				lct2=$(grep -Piowm 1 "$line" "$aallrepos") # Extráe solo la palabra lct(A####) con -o usando regex de Pearl con -P, -m 1 para que imprima la primera coincidencia y no replique los repetidos en el archivo aallrepos
				if [ "$lct2" == "$line" ]; then
				# rsync copying with full path
					fuente="${asourcepath}./${lct}"
					rsync -ahR --info=progress2 --log-file="$rsynclog" "$fuente" "$destino"
					copiados=$(echo -e "  * $line" >> "$copiadoslog")
					let counterc=counterc+1
				else
					fallidos=$(echo -e "  * $line" >> "$fallidoslog")
					let counterf=counterf+1
				fi
			done
		fi
      let totalpedido=counterc+counterf
      pedido=$(cat "$origen")
      dialog --title "Copia Finalizada" \
      --msgbox "\n
	  ------------ Rutas ------------\n
        Lista ID's  : $origen\n
            Destino : $destino\n
	  ------------ Items ------------\n
       ----------------+-----\n
        Total Pedidos  |  $totalpedido   \n
       ----------------+-----\n
        Total Copiados |  $counterc   \n
       ----------------+-----\n
        total Fallidos |  $counterf   \n
       ----------------+-----\n
      Items Pedidos:\n
      $pedido\n\n" 0 0
      exec cat -n "$copiadoslog"
      ;;
    7)
# LIBROS BY BOOKs ID
      counterc=0
      counterf=0
      regdate=$(date)
      cliente=$(dialog --stdout --title "Datos Cliente:" --inputbox "Nombre y Apellido (Prefijo):" 0 0)
      logcopy=$(echo -e "\n\n--Cliente: $cliente - $regdate" >> "$copiadoslog")
      logrip=$(echo -e "\n\n--Cliente: $cliente - $regdate" >> "$fallidoslog")
      destino=$(dialog --stdout --title "Seleccionar Carpeta Destino:" --fselect "$dialogdest" 45 125)
      origen=$(dialog --stdout --title "Ruta Lista (ej. lcid.txt)" --fselect "$dialogorig" 45 65)
      # radiolist
      pathrsyncing=$(dialog --stdout --title "RSYNC OPTION" --radiolist "Copiar el directorio/archivo con o sin el árbol de directorio" 0 70 0 \
		"1" "Sin Full Path rsync -ah ex: dir-N### or file-N###" on \
		"2" "Full Path rsync -ahR ex: /path1/to/others/target" off)
		if [ "$pathrsyncing" == 1 ]; then
      sed -i '/^[[:space:]]*$/d' "$origen"
			lowtoupcase=$(sed -i "s/l/L/g" "$origen")
			exec < "$origen"
			while read -r line
			do
				lct=$(cat "$lallrepos" | grep -iwm 1 "$line")
				lct2=$(grep -Piowm 1 "$line" "$lallrepos") # Extráe solo la palabra lct(L####) con -o usando regex de Pearl con -P, -m 1 para que imprima la primera coincidencia y no replique los repetidos en el archivo lallrepos
				if [ "$lct2" == "$line" ]; then
				# rsync copying with full path
					fuente="${lsourcepath}${lct}"
					rsync -ah --info=progress2 --log-file="$rsynclog" "$fuente" "$destino"
					copiados=$(echo -e "  * $line" >> "$copiadoslog")
					let counterc=counterc+1
				else
					fallidos=$(echo -e "  * $line" >> "$fallidoslog")
					let counterf=counterf+1
				fi
			done
		else
      sed -i '/^[[:space:]]*$/d' "$origen"
			lowtoupcase=$(sed -i "s/l/L/g" "$origen")
			exec < "$origen"
			while read -r line
			do
				lct=$(cat "$lallrepos" | grep -iwm 1 "$line")
				lct2=$(grep -Piowm 1 "$line" "$lallrepos") # Extráe solo la palabra lct(L####) con -o usando regex de Pearl con -P, -m 1 para que imprima la primera coincidencia y no replique los repetidos en el archivo lallrepos
				if [ "$lct2" == "$line" ]; then
				# rsync copying with full path
					fuente="${lsourcepath}./${lct}"
					rsync -ahR --info=progress2 --log-file="$rsynclog" "$fuente" "$destino"
					copiados=$(echo -e "  * $line" >> "$copiadoslog")
					let counterc=counterc+1
				else
					fallidos=$(echo -e "  * $line" >> "$fallidoslog")
					let counterf=counterf+1
				fi
			done
		fi
      let totalpedido=counterc+counterf
      pedido=$(cat "$origen")
      dialog --title "Copia Finalizada" \
      --msgbox "\n
	  ------------ Rutas ------------\n
        Lista ID's  : $origen\n
            Destino : $destino\n
	  ------------ Items ------------\n
       ----------------+-----\n
        Total Pedidos  |  $totalpedido   \n
       ----------------+-----\n
        Total Copiados |  $counterc   \n
       ----------------+-----\n
        total Fallidos |  $counterf   \n
       ----------------+-----\n
      Items Pedidos:\n
      $pedido\n\n" 0 0
      exec cat -n "$copiadoslog"
      ;;
    8)
# COMICS BY COMICs ID
      counterc=0
      counterf=0
      regdate=$(date)
      cliente=$(dialog --stdout --title "Datos Cliente:" --inputbox "Nombre y Apellido (Prefijo):" 0 0)
      logcopy=$(echo -e "\n\n--Cliente: $cliente - $regdate" >> "$copiadoslog")
      logrip=$(echo -e "\n\n--Cliente: $cliente - $regdate" >> "$fallidoslog")
      destino=$(dialog --stdout --title "Seleccionar Carpeta Destino:" --fselect "$dialogdest" 45 125)
      origen=$(dialog --stdout --title "Ruta Lista (ej. ccid.txt)" --fselect "$dialogorig" 45 65)
      # radiolist
      pathrsyncing=$(dialog --stdout --title "RSYNC OPTION" --radiolist "Copiar el directorio/archivo con o sin el árbol de directorio" 0 70 0 \
		"1" "Sin Full Path rsync -ah ex: dir-N### or file-N###" on \
		"2" "Full Path rsync -ahR ex: /path1/to/others/target" off)
		if [ "$pathrsyncing" == 1 ]; then
      sed -i '/^[[:space:]]*$/d' "$origen"
			lowtoupcase=$(sed -i "s/c/C/g" "$origen")
			exec < "$origen"
			while read -r line
			do
				lct=$(cat "$callrepos" | grep -iwm 1 "$line")
				lct2=$(grep -Piowm 1 "$line" "$callrepos") # Extráe solo la palabra lct(C####) con -o usando regex de Pearl con -P, -m 1 para que imprima la primera coincidencia y no replique los repetidos en el archivo callrepos
				if [ "$lct2" == "$line" ]; then
				# rsync copying with full path
					fuente="${csourcepath}${lct}"
					rsync -ah --info=progress2 --log-file="$rsynclog" "$fuente" "$destino"
					copiados=$(echo -e "  * $line" >> "$copiadoslog")
					let counterc=counterc+1
				else
					fallidos=$(echo -e "  * $line" >> "$fallidoslog")
					let counterf=counterf+1
				fi
			done
		else
      sed -i '/^[[:space:]]*$/d' "$origen"
			lowtoupcase=$(sed -i "s/c/C/g" "$origen")
			exec < "$origen"
			while read -r line
			do
				lct=$(cat "$callrepos" | grep -iwm 1 "$line")
				lct2=$(grep -Piowm 1 "$line" "$callrepos") # Extráe solo la palabra lct(C####) con -o usando regex de Pearl con -P, -m 1 para que imprima la primera coincidencia y no replique los repetidos en el archivo callrepos
				if [ "$lct2" == "$line" ]; then
				# rsync copying with full path
					fuente="${csourcepath}./${lct}"
					rsync -ahR --info=progress2 --log-file="$rsynclog" "$fuente" "$destino"
					copiados=$(echo -e "  * $line" >> "$copiadoslog")
					let counterc=counterc+1
				else
					fallidos=$(echo -e "  * $line" >> "$fallidoslog")
					let counterf=counterf+1
				fi
			done
		fi
      let totalpedido=counterc+counterf
      pedido=$(cat "$origen")
      dialog --title "Copia Finalizada" \
      --msgbox "\n
	  ------------ Rutas ------------\n
        Lista ID's  : $origen\n
            Destino : $destino\n
	  ------------ Items ------------\n
       ----------------+-----\n
        Total Pedidos  |  $totalpedido   \n
       ----------------+-----\n
        Total Copiados |  $counterc   \n
       ----------------+-----\n
        total Fallidos |  $counterf   \n
       ----------------+-----\n
      Items Pedidos:\n
      $pedido\n\n" 0 0
      exec cat -n "$copiadoslog"
      ;;
    9)
      submenu
      ;;
    0)
      test -f $copiadoslog
      dialog --clear --title "Log Archivos Copiados" --textbox "$copiadoslog" 0 0
      ;;
    10)
      dialog --title "Configuraciones" --msgbox "\
      Paths Origin/Target\n
      Origin   : $dialogorig\n
      Target 1 : $dialogdest\n
      Target 2 : $dialogdest2\n
      Target 3 : $dialogdest3\n\\n
      Repository Paths\n\n
      Music Path Source:  $msourcepath\n
      Film Path Source:   $fsourcepath\n
      Comics Path Source: $csourcepath\n
      Book Path Source:   $lsourcepath\n
      Game Path Source:   $jsourcepath\n 
      Apps Path Source:   $asourcepath\n\n
      Bases de Datos\n\n
      Music DB: $mallrepos\n
      Film DB:  $fallrepos\n
      Comic DB: $callrepos\n
      Book DB:  $lallrepos\n
      Game DB:  $jallrepos\n
      Apps DB:  $aallrepos\n\n" 31 81
      ;;
  esac
done
