#!/bin/bash
#
# Variable dryncs Config File
#
# Put full path for variables.

# For test this script you can test populating dirs and files with
# populate-dirs-files
# populate-dirs-files-ns2
# just run in console:
#   chmod a+rw populate-dirs-files populate-dirs-files-ns2
#   mkdir /test
#   cd test
#   ./populate-dirs-files
#   ./populate-dirs-files-ns2

###############
#    CONFIG   #
###############

# Origin/Target Paths for copy
#
# if you change the default path, you need
# create this directories and files manually with the same names

# Target and Source path, you can leave in blank. Other example:
# if you have samba moint point, this need to be mounted firsth
# //ip/shared-resource
# or locally with simple slash /
# or to the anywhere

# With dialog you can change the target folder, but you can
# change here with the default target folder if you want.

dialogdest="/cygdrive/"
dialogdest2="$HOME/"
dialogdest3="$HOME/"

# dialogorig var. This file content the names
# of Music dirs/files to copy, example: Copy a Dirs where i have a identifier
# number like dirM001, dirM002. So you need write this series M001 and M002
# to the other place like a usb memory, the file name doesn't matter.
# Just write line by line in a text for example: i-need-copy-this-dirs.txt
#     M001
#     M002

# Lista de Pedido. Source path/Ruta Origen.
# Navigate and choice by example i-need-copy-this-dirs.txt

dialogorig="/path/to/dryncs.git/"

# DATABASE PATHs
# 
# Importante!!! ejecute siempre la 'opción 9 Actualizar Base de Datos' cuando
# haya modificado o aumentado más directorios
#
# Fill with full path, example /path/to/mallrepos

mallrepos="/path/to/dryncs.git/mallrepos"
fallrepos="/path/to/dryncs.git/fallrepos"
callrepos="/path/to/dryncs.git/callrepos"
lallrepos="/path/to/dryncs.git/lallrepos"
jallrepos="/path/to/dryncs.git/jallrepos"
aallrepos="/path/to/dryncs.git/aallrepos"

# REPOSITORY PATH
#
# Source path to directories/Files to copy. If you change the source path
# you need update with 9 option in the program
#
# Ejemplo
# Music Source
# msourcepath="$HOME/Programs/REPO_MUSICA/"
#
# In Cygwin
# fsourcepath="/cygdrive/unidad/REPO_PELICULAS/"
#
# In Linux
# asourcepath="/path/to/REPO_APPS/"

msourcepath="/path/to/M/"
fsourcepath="/path/to/F/"
csourcepath="/path/to/C/"
lsourcepath="/path/to/L/"
jsourcepath="/path/to/J/"
asourcepath="/path/to/A/"

# Path Logs
#
# Remember put the full path, example /path/to/copiados.log

copiadoslog="/path/to/dryncs.git/copiados.log"

# Log failed Copied

fallidoslog="/path/to/dryncs.git/fallidos.log"

# Log rsync

rsynclog="/path/to/dryncs.git/dryncs.log"

################
#  END CONFIG  #
################
